config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  # サインアップ
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ログアウト
  delete '/logout', to: 'sessions#destroy'
  # 基本情報の編集
  get '/edit_basic_info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update_basic_info', to: 'users#update_basic_info'
  # 勤怠情報の編集
  get '/users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch '/users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  # 1ヶ月分勤怠申請/showページ右下申請ボタン
  patch 'users/:id/attendances/:id/update_month', to: 'attendances#update_month', as: :update_month
  # 1ヶ月分勤怠申請/モーダル表示
  get 'users/:id/attendances/:id/month_approval', to: 'attendances#month_approval', as: :month_approval
  # 1ヶ月分勤怠申請/モーダル内/変更送信ボタン
  patch 'users/:id/attendances/:id/update_approval', to: 'attendances#update_approval', as: :update_approval
  # 勤怠変更申請
  patch 'users/:id/attendances/:id/update_attendance', to: 'attendances#update_attendance', as: :update_attendance
  # 勤怠変更申請/モーダル表示
  get 'users/:id/attendances/:id/attendance_approval', to: 'attendances#attendance_approval', as: :attendance_approval
  # 勤怠変更申請/モーダル内/変更送信ボタン
  patch 'users/:id/attendances/:id/update_applicability', to: 'attendances#update_applicability', as: :update_applicability
  # 勤怠修理ログページ
  get 'users/:id/attendances/:date/attendance_log', to: 'attendances#attendance_log', as: :attendance_log
  # 残業申請ボタン押下時のモーダル表示
  get 'users/:id/attendances/:id/overtime_application', to: 'attendances#overtime_application', as: :overtime_application
  # モーダル内から残業申請
  patch 'users/:id/attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime
  # 残業申請お知らせリンクからモーダル表示
  get 'users/:id/attendances/:id/overtime_approval', to: 'attendances#overtime_approval', as: :overtime_approval
  # モーダル内の上長から残業申請の承認・否認
  patch 'users/:user_id/attendances/:id/update_overtime_approval', to: 'attendances#update_overtime_approval', as: :update_overtime_approval

  resources :users do
    get 'currently_working', on: :collection
    member do # memberルーティングは生成するurlに:idが自動付与→/users/:id/edit_personal_info
      # ユーザ情報の編集（indexページ）
      get 'edit_personal_info'
      patch 'update_personal_info'
    end
    resources :attendances
    collection { post :import } # CSVルーティング/collectionルーティングは:idが付与されない→/users/import
  end
  
  # 拠点情報ルーティング
  resources :bases
end

app/models/user.rb
class User < ApplicationRecord
  # Userモデルから見たAttendanceモデルは1対多
  # dependent: :destroy → Userを削除すると関連するAttendanceデータも同時に削除
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  validates :affiliation, length: { in: 3.. 50 }, allow_blank: true
  
  # 指定勤務時間と基本勤務時間がない場合のエラー処理
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  
  # 指定勤務開始時間と指定勤務終了時間がない場合のエラー処理
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションの為にユーザーをデータベースに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # 検索機能
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
  
  # CSV機能
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(name: row["name"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time",
    "designated_work_start_time", "designated_work_end_time", "admin", "password"]
  end

  # 自分以外の上長id(1ヶ月申請)
  def self.applied_superior(superior_id: user)
    joins(:attendances).where.not(attendances: {user_id: superior_id}).distinct
  end

  # 自分以外の上長id(勤怠変更申請)
  def self.applied_superior_at(superior_id_at: user)
    joins(:attendances).where.not(attendances: {user_id: superior_id_at}).distinct
  end

  # 自分以外の上長id(残業申請)
  def self.applied_superior_over(superior_id_over: user)
    joins(:attendances).where.not(attendances: {user_id: superior_id_over}).distinct
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, 
          :update_basic_info, :edit_personal_info, :update_personal_info]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  before_action :url_confirmation_show_page, only: :show
  before_action :url_confirmation_page, only: [:index, :currently_working]
  before_action :url_admin_show_page, only: :show
  before_action :url_superior_to_admin_show, only: :show
  
  protect_from_forgery :except => [:import]
  
  def index
    @users = User.all
    @user = User.new
    # @users = User.paginate(page: params[:page]).search(params[:search])
    # @user = User.find_by(id: params[:id])
  end
  
  def import
    @users = User.all
    # fileはtmpに自動で一時保存される
    if params[:file].present?
      User.import(params[:file])
      flash[:success] = "ユーザー情報をCSVインポートしました。"
      redirect_to users_url
    elsif params[:file].nil?
      flash.now[:danger] = "ユーザー情報のCSVインポートに失敗しました。"
      render :index
    end
  end
  
  def edit_personal_info
  end
  
  def update_personal_info
    @users = User.all
    if @user.update_attributes(personal_info_params)
      flash[:success] = "#{@user.name}さんのユーザー情報を更新しました。"
      redirect_to action: 'index'
    else
      render :index
    end
  end
  
  def show
    @user = User.find(params[:id])
    # first_day: 値 ➡︎ 左のように、first_dayがキーになっている情報を受け取って@first_dayに代入
    # def first_day(date)
    #  !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
    # end
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    @attendance = User.all.includes(:attendances)
    # 1ヶ月申請数
    @month_count = Attendance.where(superior_id: current_user).where(month_check: false).where.not(apply_month: nil).count
    # 勤怠変更申請
    @attendance_change_count = Attendance.where(superior_id_at: current_user).where(attendance_check: false).count
    # 残業申請
    @overtime_count = Attendance.where(superior_id_over: current_user).where(overtime_check: false).count
    # 1ヶ月申請と残業申請の@users
    @users = User.where(admin: false).where(superior: true).where.not(id: current_user.id)
    #勤怠ログで使用
    @users_all = User.all
    # 1ヶ月申請、自分以外の上長id
    #@users = User.where(admin: false).applied_superior(superior_id: current_user.id)
    # 残業申請、自分以外の上長id
    #@users_over = User.where(admin: false).applied_superior_over(superior_id_over: current_user.id)
    # 申請上長の名前
    @superior_a = User.find_by(id: 2).name #上長A
    @superior_b = User.find_by(id: 3).name #上長A
    @superior_c = User.find_by(id: 4).name #上長A
    #CSV出力
    respond_to do |format|
      format.html
      format.csv do
        #csv用の処理を書く
        send_data render_to_string, filename: "#{current_user.name} 勤怠情報 #{params[:first_day].to_date.strftime("%Y年%m月")}.csv", type: :csv
      end
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}を削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
      redirect_to @user
    else
      render "edit_basic_info"
    end
  end
  
  # 出勤中社員一覧
  def currently_working
    @working_users = User.all.includes(:attendances)
  end


  private
  
    def overwork_params
      params.permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
  
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, 
        :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_work_time, :work_time,
        :designated_work_start_time, :designated_work_end_time)
    end
    
    def personal_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, 
        :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    # beforeアクション
    def set_user
      @user = User.find(params[:id])
    end
    
    # ログイン済みのユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインして下さい。"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    # showページ：他のユーザーのページをURL上で入力しても拒否
    def url_confirmation_show_page
      unless current_user.superior?
        unless @user.id == @current_user.id
          flash[:danger] = "ユーザー情報の閲覧・編集はできません。"
          redirect_to root_url
        end
      end
    end

    # adminユーザー以外、URL直接入力してもページを開けない
    def url_confirmation_page
      unless current_user.admin?
        flash[:danger] = "一般ユーザーの閲覧はできません。"
        redirect_to root_url
      end
    end

    # 管理者自身がURL直接入力するとtopページに戻る
    def url_admin_show_page
      if current_user.admin?
        redirect_to root_url
      end
    end

    #上長ユーザーは管理者勤怠showページを閲覧不可
    def url_superior_to_admin_show
      if current_user.superior?
        if @user.id == 1
          redirect_to root_url
        end
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
  # 基本時間・指定勤務時間などをフォーマット化
  def format_basic_info(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min) / 60.0)
  end
  
#   (例) 18:30 => 18.5
# “%.2f”, ((datetime.hour * 60) + datetime.min)/60.0)

# a = 18(datetime.hour) * 60 == 1080
# b = 30(datetime.min)
# c = a + b ==  1110 / 60.0
# c = 18.5

# %.2f => 「小数点2までを表示する」という意味(18.25の場合もあるため)


# 今回の例としてあげたパターンだと、
# ・「全体をまず分単位で統一する」　18時*60 == 1080分
# ・1080分 + 30分 = 1110分
# ・1110分を時間単位に戻す。
# ・1110分/60.0(小数点0をつけないと0.5が表示されない。切り捨て) = 18.5

end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_header_info_table.html.erb
<div class="container" style="margin-top: 20px;">
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <% if current_user.id? %>
        <div class="btn-users-show" style="font-size: 20px;">
          <% if @user.id == current_user.id || current_user.admin %>
            <%= link_to "◀︎", user_path(params: {id: @user.id, first_day: @first_day.prev_month }), class: "btn btn-primary btn-xs" %>
            <%= l(@first_day, format: :long) %>
            <%= link_to "▶︎", user_path(params: {id: @user.id, first_day: @first_day.next_month }), class: "btn btn-primary btn-xs" %>
          <% end %>
        </div>
      <% end %>
    </tr>
  </table>
</div>

app/views/users/_month_attendance_update.html.erb
<%= form_with model: @user, url: update_month_path(@user.id), method: :patch do |f| %>
  <% @users.each do |user| %> <!--自分以外の上長idを含む@users-->
    <% @dates.each do |day| %>
      <!--attendances[] ➡︎ 各フォームのinputタグのname属性にattendances[id][カラム名]という形式で展開-->
      <!--dayは繰り返し処理されている@datesからなる1つのAttendanceオブジェクト-->
      <%= f.fields_for "attendances[]", day do |af| %>
        <div class="form-group">
          <% superior_name = "" %>
          <% if day.superior_id == 2 %>
            <% superior_name = @superior_a %>
          <% elsif day.superior_id == 3 %>
            <% superior_name = @superior_b %>
          <% elsif day.superior_id == 4 %>
            <% superior_name = @superior_c %>
          <% end %>
          <!--承認 && チェックON-->
          <% if day.month_approval == "承認" && day.month_check == true %>
            <div class="success_color"><p>所属長承認【承認済】: <%= superior_name %></p></div>
          <!--否認 && チェックON-->
          <% elsif day.month_approval == "否認" && day.month_check == true %>
            <div class="danger_color"><p>所属長承認【否認】: <%= superior_name %></p></div>
          <!--申請中-->
          <% elsif day.superior_id.present? %>
            <label for="select1a" class="label_font">所属長承認【申請中】: <%= superior_name %></label>
          <!--その他、未申請時-->
          <% else %>
            <label for="select1a" class="label_font">所属長承認 未</label>
          <% end %>
          <!--申請後、申請先ユーザーとメッセージ表示、申請ボタンにて値がリセットされる-->
          <% if @user.id == current_user.id %>
            <!--一つ目id: value, 二つ目name: 表示用-->
            <!--申請先上長のid(superior_id)を選択-->
            <%= af.collection_select :superior_id, @users, :id, :name, {include_blank: true, selected: nil}, {class: "form-control"} %>
            <!--申請月の@first_dayを自動で渡す-->
            <%= af.hidden_field :apply_month, :value => @first_day %>
            <!--裏側でmonth_approval == "申請中"を渡したい-->
            <%= af.hidden_field :month_approval, value: "申請中" %>
            <!--裏側でmonth_check == falseにしたい-->
            <%= af.hidden_field :month_check, :value => false %>
          <% end %>
        </div>
      <% end %>
      <!--attendanceカラム使用するためdayをeachで回しているので1ヶ月表示→breakで断ち切る-->
      <% break %>
    <% end %>
    <% break %>
  <% end %>
  <div class="btn-attendances-center">
    <% if @user.id == current_user.id %>
      <%= f.submit "申請", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/users/_notice.html.erb
<!--１ヶ月申請が１件以上、かつ現在ログイン中Userの場合-->
<% if @month_count > 0 && current_user?(@user) %>
  <p class="notice">【所属長承認申請のお知らせ】<%= link_to "#{@month_count}件の通知があります", month_approval_path(@user), remote: true, class: "notice_radius" %></p>
<% else %>
  <p class="notice_black">【所属長承認申請のお知らせ】</p>
<% end %>
<!--所属長申請モーダルウインドウ表示-->
<div id="month_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--勤怠変更申請が１件以上、かつ現在ログイン中Userの場合-->
<% if @attendance_change_count > 0 && current_user?(@user)  %>
  <p class="notice">【勤怠変更申請のお知らせ】<%= link_to "#{@attendance_change_count}件の通知があります", attendance_approval_path(@user), remote: true, class: "notice_radius" %></p>
<% else %>
  <p class="notice_black">【勤怠変更申請のお知らせ】</p>
<% end %>
<!--勤怠変更申請モーダルウインドウ表示-->
<div id="attendance_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<!--勤怠変更申請が１件以上、かつ現在ログイン中Userの場合-->
<% if @overtime_count > 0 && current_user?(@user)  %>
  <p class="notice">
    【残業申請のお知らせ】
    <%= link_to "#{@overtime_count}件の通知があります", overtime_approval_path(@user), remote: true, class: "notice_radius" %>
  </p>
<% else %>
  <p class="notice_black">【残業申請のお知らせ】</p>
<% end %>
<!--残業申請モーダルウインドウ表示-->
<div id="overtime_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/_user.html.erb
<%= form_with(model: user, url: update_personal_info_user_path(user), local: true, method: :patch) do |f| %>
  <div class="col-xs-12">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <!--所属-->
    <%= f.label :affiliation %>
    <%= f.text_field :affiliation, class: 'form-control' %>
    
    <!--社員番号-->
    <%= f.label :employee_number %>
    <%= f.text_field :employee_number, class: 'form-control' %>
    
    <!--カードID-->
    <%= f.label :uid %>
    <%= f.text_field :uid, class: 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  
    <!--基本勤務時間-->
    <%= f.label :basic_work_time %>
    <%= f.time_field :basic_work_time, class: 'form-control' %>
    
    <!--指定勤務開始時間-->
    <%= f.label :designated_work_start_time %>
    <%= f.time_field :designated_work_start_time, class: 'form-control' %>
    
    <!--指定勤務終了時間-->
    <%= f.label :designated_work_end_time %>
    <%= f.time_field :designated_work_end_time, class: 'form-control' %>
    
    <%= f.submit "編集する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/currently_working.html.erb
<% provide(:title, "出勤社員一覧") %>
<h1>出勤中社員一覧</h1>

<table class="table table-striped table-bordered table-condensed table-hover user-table">
  <thead>
    <tr>
      <th class="col-xs-4">社員番号</th>
      <th class="col-xs-8">名前</th>
    </tr>
  </thead>
  
  <tbody>
    <% @working_users.each do |working_user| %>
      <% working_user.attendances.each do |worker| %>
        <% if worker.worked_on == Date.today && worker.started_at.present? && worker.finished_at.blank? %>
          <tr>
            <td><%= working_user.employee_number %></td>
            <td><%= working_user.name %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
  
</table>

app/views/users/edit.html.erb
<%= provide(:title, "アカウント編集") %>
<%= provide(:button_text, "編集") %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報修正") %>

<h1>基本情報の修正</h1>

<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
    <%#= form_with(model: @user, url: update_basic_info_path(params: {id: @user.id}), local: true, method: :patch) do |f| %>
      <%#= render 'shared/error_messages', model: f.object %>

      <%#= f.label :work_time, class:'control-label' %>
      <%#= f.time_field :work_time, class: 'form-control' %>

      <%#= f.label :basic_work_time %>
      <%#= f.time_field :basic_work_time, class: 'form-control' %>

      <%#= f.label :designated_work_start_time %>
      <%#= f.time_field :designated_work_start_time, class: 'form-control' %>

      <%#= f.label :designated_work_end_time %>
      <%#= f.time_field :designated_work_end_time, class: 'form-control' %>
    
      <%#= f.submit "更新する", class: "btn btn-primary" %>
    <%# end %>
<!--  </div>-->
<!--</div>-->

app/views/users/edit_overwork_receive.js.erb
$("#edit_overwork_receive").html("<%= escape_javascript(render 'edit_overwork_receive') %>");
$("#edit_overwork_receive").modal("show");

app/views/users/edit_overwork_request.js.erb
$("#edit_overwork_request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit_overwork_request").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>
<div class="col-md-10 col-md-offset-1">
  <table class="table table-hover" id="table-users">
    <!--CSVインポート-->
    <div class="row">
      <div class="col-md-4">
        <%= form_tag import_users_path, multipart: true do %>
          <%= file_field_tag :file, { class: "form-control" } %>
          <%= submit_tag "CSVインポート", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <% @users.each do |user| %>
      <tr class="user_font">
        <td>
          <div id="user-position">
            <%= user.name %><br>
            <% if current_user.admin? %>
              <% if not current_user?(user) %>
                <%= link_to "削除", user, method: :delete, class: "btn btn-primary", data: { confirm: "削除しますか?" } %><br>
              <% end %>
            <% end %>
          </div>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" href="#collapse<%= user.id %>"><button type="submit" class="btn btn-primary">編集</button></a>
                </h4>
              </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                <ul class="list-group">
                  <%= render "user", {user: user} %>
                </ul>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, "SignUp") %>
<% provide(:button_text, "アカウント作成") %>

<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render 'header_info_table' %>

<table class="table table-striped table-bordered table-condensed user-table">
  <thead>
    <tr style="background: #FFFFBB; font-size: 20px;">
      <th rowspan="3"><%= l(@first_day, format: :long) %></th>
      <th>10:00</th>
      <td>10:30</td>
      <th>11:00</th>
      <td>11:30</td>
<!--      <th>12:00</th>-->
<!--      <td>12:30</td>-->
<!--      <th>13:00</th>-->
<!--      <td>13:30</td>-->
      <th>14:00</th>
      <td>14:30</td>
      <th>15:00</th>
      <td>15:30</td>
<!--      <th>16:00</th>-->
<!--      <td>16:30</td>-->
<!--      <th>17:00</th>-->
<!--      <td>17:30</td>-->
<!--      <th>18:00</th>-->
    </tr>
  </thead>
  <tbody>
    <%= render 'show_body' %>
  </tbody>

</table>

<!--モーダルウインドウ表示-->
<div id="reserve" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>