config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  # サインアップ
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  # ログアウト
  delete '/logout', to: 'sessions#destroy'
  # 基本情報の編集
  get '/edit_basic_info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update_basic_info', to: 'users#update_basic_info'
  # 勤怠情報の編集
  get '/users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch '/users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  # 1ヶ月分勤怠申請/showページ右下申請ボタン
  patch 'users/:id/attendances/:id/update_month', to: 'attendances#update_month', as: :update_month
  # 1ヶ月分勤怠申請/モーダル表示
  get 'users/:id/attendances/:id/month_approval', to: 'attendances#month_approval', as: :month_approval
  # 1ヶ月分勤怠申請/モーダル内/変更送信ボタン
  patch 'users/:id/attendances/:id/update_approval', to: 'attendances#update_approval', as: :update_approval
  # 勤怠変更申請
  patch 'users/:id/attendances/:id/update_attendance', to: 'attendances#update_attendance', as: :update_attendance
  # 勤怠変更申請/モーダル表示
  get 'users/:id/attendances/:id/attendance_approval', to: 'attendances#attendance_approval', as: :attendance_approval
  # 勤怠変更申請/モーダル内/変更送信ボタン
  patch 'users/:id/attendances/:id/update_applicability', to: 'attendances#update_applicability', as: :update_applicability
  # 勤怠修理ログページ
  get 'users/:id/attendances/:date/attendance_log', to: 'attendances#attendance_log', as: :attendance_log
  # 残業申請ボタン押下時のモーダル表示
  get 'users/:id/attendances/:id/overtime_application', to: 'attendances#overtime_application', as: :overtime_application
  # モーダル内から残業申請
  patch 'users/:id/attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime
  # 残業申請お知らせリンクからモーダル表示
  get 'users/:id/attendances/:id/overtime_approval', to: 'attendances#overtime_approval', as: :overtime_approval
  # モーダル内の上長から残業申請の承認・否認
  patch 'users/:user_id/attendances/:id/update_overtime_approval', to: 'attendances#update_overtime_approval', as: :update_overtime_approval

  resources :users do
    get 'currently_working', on: :collection
    member do # memberルーティングは生成するurlに:idが自動付与→/users/:id/edit_personal_info
      # ユーザ情報の編集（indexページ）
      get 'edit_personal_info'
      patch 'update_personal_info'
    end
    resources :attendances
    collection { post :import } # CSVルーティング/collectionルーティングは:idが付与されない→/users/import
  end
  
  # 拠点情報ルーティング
  resources :bases
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # Attendanceモデルから見たuserモデルとの関連性は1対1
  belongs_to :user

  # 日付は必須
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  # 出社時間が無ければ退社時間は無効
  validate :finished_at_is_invalid_without_started_at
  
  # 退社時間を保存する時、出社時間より早い時間の場合は無効
  #validate :invalid_started_at_is_faster_than_finished_at
  
  # 出社時間が無ければ退社時間は無効
  def finished_at_is_invalid_without_started_at
    errors.add(:started_at, "が必要です。") if started_at.blank? && finished_at.present?
  end
  
  # 退社時間を保存する時、出社時間より早い時間の場合は無効
  # started_at > finished_atになる事はまずない。
  # 理由は勤怠編集ページで扱うカラムはchange_〇〇。実際の出退勤ボタン押下時も上記条件になる事はまずない。
  # 翌日チェックの際に、勤怠編集モーダルからhidden_fieldで自動で値が送られる際に無駄に引っかかってしまう。
  #def invalid_started_at_is_faster_than_finished_at
  #  if started_at.present? && finished_at.present?
  #    errors.add(:started_at, "より早い退勤時刻は無効です。") if started_at > finished_at
  #  end
  #end

  # 1ヶ月勤怠申請
  enum month_approval: { "申請中" => 1, "承認" => 2, "否認" => 3, "なし" => 4 }, _suffix: true # 同じenum名定義できる
  # 勤怠変更申請
  enum attendance_approval: {"申請中" => 1, "承認" => 2, "否認" => 3, "なし" => 4}, _suffix: true
  # 残業申請
  enum overtime_approval: { "申請中" => 1, "承認" => 2, "否認" => 3, "なし" => 4}, _suffix: true
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit, :update, :update_month, :month_approval, :attendance_approval,
                                  :overtime_application, :update_approval, :update_applicability, :attendance_log,
                                  :update_overtime, :overtime_approval, :update_overtime_approval]
  before_action :url_attendances_edit, only: :edit
  before_action :url_admin_attendances_edit, only: :edit
  
  def create
    # ルーティングを確認すると、/users/:user_id/attendances → paramsでuser_idを受け取る
    @user = User.find(params[:user_id])
    # @userモデルに紐付くattendanceモデルから、find_byで日付カラムがDate.todayを探して@attendanceに代入
    # @attendanceは、つまり今日を表す
    @attendance = @user.attendances.find_by(worked_on: Date.today)
    # もし今日（@attendance）がnilだったら
    if @attendance.started_at.nil? && @attendance.change_started.nil?
      # current_time → 現在時刻を表す / attendance_helper.rb参照
      # @attendanceのstarted_atカラムを現在時刻として更新
      @attendance.update_attributes(started_at: current_time.floor_to(15.minutes))
      @attendance.update_attributes(change_started: current_time.floor_to(15.minutes))
      flash[:info] = "おはようございます。"
      # started_atに値が存在していて、finished_atがnilだった場合
    elsif @attendance.finished_at.nil? && @attendance.change_finished.nil?
      # finished_atカラムを現在時刻として@attendanceを更新
      @attendance.update_attributes(finished_at: current_time.floor_to(15.minutes))
      @attendance.update_attributes(change_finished: current_time.floor_to(15.minutes))
      flash[:info] = "お疲れ様でした。"
    else
      flash[:danger] = "トラブルがあり実行できませんでした。"
    end
    redirect_to @user
  end

  # 勤怠編集画面
  def edit
    @first_day = first_day(params[:date])
    @last_day = @first_day.end_of_month
    @dates = user_attendances_month_date
    # 自分以外の上長
    @users = User.where(admin: false).where(superior: true).where.not(id: current_user.id)
  end

  # 勤怠情報update
  def update
    if attendances_invalid?
      attendances_params.each do |id, item|
        if attendance_superior_present?(item[:superior_id_at], item[:change_started], item[:change_finished])
          attendance = Attendance.find(id)
          attendance.update_attributes(item)
        end
      end
      flash[:success] = "勤怠情報を申請しました。申請できていない場合は必要項目が選択されているか確認して下さい。"
      redirect_to user_url(@user, params:{first_day: params[:date]})
    else
      flash[:danger] = "不正な時間入力がありました。出社時間と退社時間はセットで入力されているか確認して下さい。"
      redirect_to edit_attendances_path(@user, params[:date])
    end
  end

  # 勤怠変更申請表示モーダル
  def attendance_approval
    @start_time = params[:change_started]
    @users = User.applied_superior_at(superior_id_at: current_user.id)
    @first_day = first_day(params[:first_day]) # attendance_helper.rb参照
    @last_day = @first_day.end_of_month # end_od_monthは当月の終日を表す
    (@first_day..@last_day).each do |day| # 月の初日から終日までを表す
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date # 1ヶ月の情報を表す・・・attendances_helper.rb参照
  end

  # 勤怠変更申請の変更送信ボタンのアクション
  def update_applicability
    #「変更を送信する」ボタン：選択肢の確認(承認または否認、かつチェックON ➡︎ true)
    update_applicability_params.each do |id, item|
      if attendance_change_invalid?(item[:attendance_approval], item[:attendance_check]) # 処理がtrueになったら更新
        # eachで回ってきた該当するidのAttendanceオブジェクトをattendanceに代入
        attendance = Attendance.find(id)
        if item[:attendance_approval] == "否認"
          attendance.update_attributes(attendance_approval: "否認", attendance_check: "1")
        #elsif item[:attendance_approval] == "承認"
        #  attendance.update_attributes(attendance_approval: "承認", attendance_check: "1")
        else
          attendance.update_attributes!(item)
        end
      end
      #raise
    end
    flash[:success] = "勤怠変更申請返答しました。申請できていない場合は必要項目が選択されているか確認して下さい。"
    redirect_to user_path(@user)
  end

  # 勤怠ページから1ヶ月申請
  def update_month
    if superior_present? # params[:user][:apply_month] = @first_day /申請先上長が選択されているか確認
      update_month_params.each do |id, item| # idはAttendanceモデルオブジェクトのid、itemは各カラムの値が入った更新するための情報
        # 更新するべきAttendanceモデルオブジェクトを探してattendanceに代入
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
      end
      flash[:success] = "所属長申請しました。"
      redirect_to @user
    else
      flash[:danger] = "申請先を選択して下さい。"
      redirect_to @user
    end
  end

  # 1ヶ月分勤怠申請/モーダル表示
  def month_approval
    @users = User.applied_superior(superior_id: current_user.id)
  end

  # 申請の承認可否の更新
  def update_approval
    # update_approval_paramsをeachで回す
    update_approval_params.each do |id, item|
      # もしapply_and_checkbox_invalid? ➡︎ 引数が(item[:month_approval], item[:month_check])の場合
      # each分の中にヘルパーメソッドを記入する事で毎回処理をチェックできる
      if apply_and_checkbox_invalid?(item[:month_approval], item[:month_check]) # 処理がtrueになったら更新
        # eachで回ってきた該当するidのAttendanceオブジェクトをattendanceに代入
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
      end
    end
    flash[:success] = "1ヶ月分の勤怠申請しました。申請できていない場合は必要項目が選択されているか確認して下さい。"
    redirect_to user_path(@user)
  end

  # 勤怠変更申請ログ
  def attendance_log
    @users = User.all
    # 申請上長の名前
    @superior_a = User.find_by(id: 2).name #上長A
    @superior_b = User.find_by(id: 3).name #上長B
    @superior_c = User.find_by(id: 4).name #上長C
  end

  # 残業申請ボタン押下時モーダル表示
  def overtime_application
    @users = User.where(admin: false).applied_superior_over(superior_id_over: current_user.id)
    @attendance = Attendance.find(params[:id])
    @dates = user_attendances_month_date # 1ヶ月の情報を表す・・・attendances_helper.rb参照
    # showページから送られてくるdayキーに格納されている情報をparamsで受信
    @day = Date.parse(params[:day])
  end

  def update_overtime
    update_overtime_params.each do |id, item|
      attendance = Attendance.find(id)
      attendance.update_attributes(item)
      if item[:reserve_check] == "true"
        flash[:success] = "予約確定しました。"
      else
        flash[:warning] = "予約キャンセルしました。"
      end
    end
    redirect_to user_path(@user)
  end

  def overtime_approval
    @users = User.all
  end

  def update_overtime_approval
    overtime_approval_params.each do |id, item|
      # each分の中にヘルパーメソッドを記入する事で毎回処理をチェックできる
      if overtime_approval_invalid?(item[:overtime_approval], item[:overtime_check])
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
      end
    end
    flash[:success] = "残業申請返答しました。申請できていない場合は必要項目が選択されているか確認して下さい。"
    redirect_to user_path(@user)
  end


  private

    # 勤怠変更申請
    def attendances_params
      # :attendancesがキーのハッシュの中にネストされたidと各カラムの値があるハッシュ
      # {"1" => {"started_at"=>"10:00", "finished_at"=>"18:00", "note"=>"シフトA"}
      params.require(:user).permit(attendances: [:change_started, :change_finished, :note, :tomorrow_check, :superior_id_at,
                                  :attendance_approval, :attendance_check, :apply_month_at])[:attendances]
    end

    # 勤怠変更申請モーダル内カラム
    def update_applicability_params
      params.require(:user).permit(attendances: [:attendance_approval, :attendance_check, :started_at, :finished_at])[:attendances]
    end

    # 申請した上長idと申請月
    def update_month_params
      params.require(:user).permit(attendances: [:superior_id, :apply_month, :month_approval, :month_check])[:attendances]
    end

    # 申請の承認可否の更新
    def update_approval_params
      params.require(:user).permit(attendances: [:month_approval, :month_check])[:attendances]
    end

    # 残業申請カラム
    def update_overtime_params
      params.permit(attendances: [:reserve_time, :reserve_time1030, :reserve_time1100, :reserve_time1130, :reserve_time1400,
                                  :reserve_time1430, :reserve_time1500, :reserve_time1530, :reserve_check])[:attendances]
    end

    # 残業申請承認・否認の更新
    def overtime_approval_params
      params.require(:user).permit(attendances: [:overtime_approval, :overtime_check])[:attendances]
    end

    # beforeアクション

    def set_user
      @user = User.find(params[:id])
    end

    # 自分以外の勤怠編集ページへのアクセス拒否
    def url_attendances_edit
      unless @user.id == current_user.id
        redirect_to root_url
      end
    end

    # 管理者自身の編集ページへのアクセス拒否
    def url_admin_attendances_edit
      if current_user.admin?
        if @user.id == 1
          redirect_to root_url
        end
      end
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
  # 現在時刻を表す
  def current_time
    # Time.new(　=> 現在時刻でTimeオブジェクト生成
    Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
  end
  
  # 在社時間を計算
  def working_times(started_at, finished_at)
    format("%.2f", (((finished_at - started_at) /60) / 60.0))
  end

  # 翌日チェックのある在社時間を計算
  def tomorrow_check_working_times(change_started, change_finished)
    format("%.2f", (((change_finished - change_started) /60) / 60.0) + 24)
  end
  
  # 勤務時間の合計
  def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end

  # 時間外時間を計算
  def overtime_result(work_end_time, job_end_time)
    job_end_time - work_end_time
  end
  
  # @first_dayの定義
  # まず当日を取得するためDate.currentを使用
  # これにRailsのメソッドであるbeginning_of_monthを繋げることで当月の初日を取得することが可能
  # first_dayメソッドの引数であるdateがnil(空)でなかった場合はtrueとなりDate.parse(date)、
  # nilだった場合falseとなりDate.current.beginning_of_monthとなる
  # つまり前者はdateに引数があればparse(date)で、文字列による日付をDateオブジェクトに変換
  # 後者は現在の日付から計算して月の初めの日（1日）を表す
  def first_day(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
  end

  # ユーザーに基づく1ヶ月間の値
  # UserモデルとAttendanceモデルを1対多と関連付け → @user.attendances という記法
  # @first_day以上かつ@last_day以下をwhereで範囲指定 つまり１ヶ月の情報
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  # 不正な値があるか確認する・・・変更出勤時間と変更退勤時間
  def attendances_invalid?
    attendances = true #不正な値がない状態でスタート → true
    attendances_params.each do |id, item|
      # ①出勤時間と退勤時間が空白の場合、nextで次の繰り返し処理が続行
      if item[:change_started].blank? && item[:change_finished].blank?
        next
      elsif item[:tomorrow_check] == "1" && item[:change_started].present? && item[:change_finished].present?
        next
      # ②出勤時間が空白、または退勤時間が空白の場合 → 繰り返し処理を終了しfalseを返す
      elsif item[:change_started].blank? || item[:change_finished].blank?
        attendances = false
        break
      # ③出勤時間が退勤時間より大きい場合 → 処理を終了しfalseを返す
      elsif item[:change_started] > item[:change_finished]
        attendances = false
        break
      end
    end
    # ①問題ないのでtrueを返す、②③問題ありfalseを返す
    attendances
  end

  # 1ヶ月申請「変更を送信する」ボタン：選択肢の確認
  def apply_and_checkbox_invalid?(ma, mc) # 引数：ma = item[:month_approval]、引数：mc = item[:month_check]
    # (承認or否認) かつ チェックボックスON ➡︎ 唯一trueの処理
    # mcはデバッガー確認時"0","1"でありtrue,falseではない。"◯"で文字列として扱う必要がある
    if (ma == "承認" || ma == "否認") and mc == "1" #and優先順位低い
      apply = true
    else # それ以外の処理は全てNG
      apply = false
    end
    apply
  end

  # 勤怠変更申請ボタン：選択肢の確認
  def attendance_change_invalid?(ap, check)
    # 指示者確認印が承認または否認 かつ 変更がONの時はtrue
    if (ap == "承認" || ap == "否認") and check == "1"
      apply = true
    else
      apply = false
    end
    apply
  end

  # 申請先上長が選択されているか確認
  def superior_present?
    superior = true
    update_month_params.each do |id, item|
      if item[:superior_id].blank? && [:apply_month].present?
        superior = false
      elsif item[:superior_id].present? && [:apply_month].present?
        superior = true
        break
      end
    end
    superior
  end

  # 上長が選択されていればtrueを返す(上長だけ選択して申請できなくする)
  def attendance_superior_present?(superior_id_at, start, finish)
    if superior_id_at.present? && start.present? && finish.present?
      apply = true
    else
      apply = false
    end
    apply
  end

  # 残業申請：終了予定時間と業務処理内容と上長が選択されているかチェック
  def overtime_value_present?
    overtime = true
    update_overtime_params.each do |id, item|
      if item[:job_end_time].blank? || item[:job_content].blank? || item[:superior_id_over].blank?
        overtime = false
      else
        overtime = true
      end
    end
    overtime
  end

  # 残業申請時間が勤務時間内かをチェック
  def overtime_range_invalid?
    time = @user.designated_work_end_time # 指定勤務終了時間をtimeに代入
    overtime = true
    update_overtime_params.each do |id, item|
      # 終了予定時間が指定勤務終了時間より早い場合 ➡︎ false
      if item[:tomorrow_check_over] == "1"
        next
      elsif time.strftime("%H:%M:%S") > item[:job_end_time]
        overtime = false
      end
    end
    overtime
  end

  # 残業申請ボタン：選択肢の確認
  def overtime_approval_invalid?(op, oc)
    if (op == "承認" || op == "否認") and oc == "1"
      overtime = true
    else
      overtime = false
    end
    overtime
  end

end

app/views/attendances/_attendance_approval.html.erb
<div class="modal-dialog modal-dialog-center">
  <%= form_with(model: @user, url: update_applicability_path(@user), local: true, method: :patch) do |f| %>
    <div class="modal-position">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% @users.each do |user| %>
          <div class="modal-body"> <!--モーダルボディ-->
            <table class="table table-bordered table-condensed table-hover">
              <% attendances = Attendance.where(user_id: user.id) %> <!--モーダルフッター-->
              <% attendances.each do |at| %>
                <% if at.superior_id_at == current_user.id %>
                  <% if at.attendance_approval == "申請中" || at.attendance_check == false %>
                    <h4 class="modal-title">【<%= user.name %>からの勤怠変更申請】</h4>
                      <thead class="thead_color">
                        <tr>
                          <th rowspan="3" class="title-position">日付</th>
                          <th rowspan="3" class="title-position">曜日</th>
                          <th colspan="4" class="title-position">変更前</th>
                          <th colspan="4" class="title-position">変更後</th>
                          <th rowspan="3" class="title-position">備考</th>
                          <th rowspan="3" class="title-position">指示者確認㊞</th>
                          <th rowspan="3" class="title-position">変更</th>
                          <th rowspan="3" class="title-position">勤怠を確認する</th>
                        </tr>
                        <tr>
                          <th colspan="2" class="title-position">出社</th>
                          <th colspan="2" class="title-position">退社</th>
                          <th colspan="2" class="title-position">出社</th>
                          <th colspan="2" class="title-position">退社</th>
                        </tr>
                        <tr>
                          <th class="title-position">時</th>
                          <th class="title-position">分</th>
                          <th class="title-position">時</th>
                          <th class="title-position">分</th>
                          <th class="title-position">時</th>
                          <th class="title-position">分</th>
                          <th class="title-position">時</th>
                          <th class="title-position">分</th>
                        </tr>
                      </thead>
                    <% break %>
                  <% end %>
                <% end %>
              <% end %>
              <% attendances = Attendance.where(user_id: user.id) %> <!--モーダルフッター-->
              <% attendances.each do |at| %>
                <% if at.superior_id_at == current_user.id %>
                  <% if at.attendance_approval == "申請中" || at.attendance_check == false %>
                    <%= f.fields_for "attendances[]", at do |af| %>
                      <tbody>
                      <tr>
                        <td><%= l(at.worked_on, format: :short1) %></td>
                        <td>
                          <% $days_of_the_week[at.worked_on.wday] %>
                          <!--if文でwdayが0か6（土か日曜日）だったらの時の処理-->
                          <% if at.worked_on.wday == 0 %>
                            <div class="sunday"><%= $days_of_the_week[at.worked_on.wday] %></div>
                          <% elsif at.worked_on.wday == 6 %>
                            <div class="saturday"><%= $days_of_the_week[at.worked_on.wday] %></div>
                          <% else %>
                            <%= $days_of_the_week[at.worked_on.wday] %>
                          <% end %>
                        </td>
                        <% if at.started_at.present? && at.finished_at.present? %>
                          <td><%= l(at.started_at, format: :hour) %></td>
                          <td><%= l(at.started_at.floor_to(15.minutes), format: :min) %></td>
                          <td><%= l(at.finished_at, format: :hour) %></td>
                          <td><%= l(at.finished_at.floor_to(15.minutes), format: :min) %></td>
                        <% else %>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                        <% end %>
                        <% if at.change_started.present? && at.change_finished.present? %>
                          <td><%= l(at.change_started, format: :hour) %></td>
                          <td><%= l(at.change_started.floor_to(15.minutes), format: :min) %></td>
                          <td><%= l(at.change_finished, format: :hour) %></td>
                          <td><%= l(at.change_finished.floor_to(15.minutes), format: :min) %></td>
                        <% end %>
                        <td><%= at.note %></td>
                        <td style="padding-top: 16px;">
                          <%= af.select :attendance_approval, Attendance.attendance_approvals.keys.to_a, {}, { class: "form-control" } %>
                        </td>
                        <td class="checkbox_width">
                          <%= af.check_box :attendance_check, include_hidden: false %>
                        </td>
                        <td>
                          <%= link_to "確認", user_path(id: user.id, first_day: at.apply_month_at ), class: 'btn btn-primary' %>
                        </td>
                        <%= af.hidden_field :started_at, value: at.change_started.to_time %>
                        <%= af.hidden_field :finished_at, value: at.change_finished.to_time %>
                      </tr>
                      </tbody>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
        <div class="modal-footer">
          <div id="notice-message">
            <p><img src="https://zet-art.net/wp-content/uploads/2019/03/caution-01.png" alt="注意" width="40" height="40" border="0" />①指示者確認㊞が申請中の状態だと申請できません。②申請する場合は変更にチェックを入れて下さい。</p>
          </div>
          <div id="change-btn">
            <%= f.submit "変更を送信する", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/attendances/_month_approval.html.erb
<div class="modal-dialog modal-dialog-center">
  <%= form_with(model: @user, url: update_approval_path(@user), local: true, method: :patch) do |f| %>
    <div class="modal-position">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% @users.each do |user| %>
          <div class="modal-body"> <!--モーダルボディ-->
            <table class="table table-bordered table-condensed table-hover">
              <% attendances = Attendance.where(user_id: user.id) %>
              <% attendances.each do |at| %>
                <% if at.superior_id == current_user.id %>
                  <% if at.month_approval == "申請中" || at.month_check == false %>
                    <% if at.apply_month.present? %> <!--1ヶ月申請特有のapply_monthカラムで表示可否判定-->
                      <h4 class="modal-title" style="padding-bottom: 10px;">【<%= user.name %>からの１ヶ月分勤怠申請】</h4>
                        <thead style="background: #F7F7F7">
                          <tr>
                            <th class="title-position">月</th>
                            <th class="title-position">指示者確認㊞</th>
                            <th class="title-position">変更</th>
                            <th class="title-position">勤怠を確認する</th>
                          </tr>
                        </thead>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
              <% attendances = Attendance.where(user_id: user.id) %> <!--モーダルヘッダー-->
              <% attendances.each do |at| %>
                <% if at.superior_id == current_user.id %>
                  <% if at.month_approval == "申請中" || at.month_check == false %>
                    <% if at.apply_month.present? %> <!--1ヶ月申請特有のapply_monthカラムで表示可否判定-->
                      <%= f.fields_for "attendances[]", at do |af| %>
                        <tbody>
                          <tr>
                            <td><%= l(at.apply_month, format: :month) %></td>
                            <td style="padding-top: 16px">
                              <%= af.select :month_approval, Attendance.month_approvals.keys.to_a, {}, { class: "form-control" } %>
                            </td>
                            <td class="checkbox_width">
                              <%= af.check_box :month_check, include_hidden: false %>
                            </td>
                            <td>
                              <%= link_to "確認", user_path(id: user.id, first_day: at.apply_month ), class: 'btn btn-primary' %>
                            </td>
                          </tr>
                        </tbody>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
        <div class="modal-footer">
          <p><img src="https://zet-art.net/wp-content/uploads/2019/03/caution-01.png" alt="注意" width="40" height="40" border="0" />①指示者確認㊞が申請中の状態だと申請できません。②申請する場合は変更にチェックを入れて下さい。</p>
          <div id="change-btn">
            <%= f.submit "変更を送信する", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/attendances/attendance_approval.js.erb
$("#attendance_approval").html("<%= escape_javascript(render 'attendance_approval') %>");
$("#attendance_approval").modal("show");

app/views/attendances/month_approval.js.erb
$("#month_approval").html("<%= escape_javascript(render 'month_approval') %>");
$("#month_approval").modal("show");

app/views/attendances/overtime_approval.js.erb
$("#overtime_approval").html("<%= escape_javascript(render 'overtime_approval') %>");
$("#overtime_approval").modal("show");